channels:
    - conda-forge
dependencies:
    - python
    - pip
    - setuptools
    - matplotlib
    - jupyterlab
    - numpy
    - scikitlearn
    - pandas
    - nbconvert
    - seaborn
    - pip:
      - jupyterlab_latex
