channels:
    - conda-forge
dependencies:
    - python
    - pip
    - setuptools
    - matplotlib
    - jupyterlab
    - numpy
    - scikit-learn
    - pandas
    - nbconvert
    - seaborn
    - pip:
      - jupyterlab_latex
